import React from 'react'

export const metadata = {
    title: "Show Task : Work Manager",
    //description: "Generated by create next app",
  };

const ShowTask = () => {
  return (
    <div>
      <h1>This is a show task page.</h1>
    </div>
  )
}

export default ShowTask;
