import React from 'react'

export const metadata = {
    title: "Add Task : Work Manager",
    //description: "Generated by create next app",
  };

const AddTask = () => {
  return (
    <div>
      <h1 className='text-3xl'>Add Task Components</h1>
    </div>
  )
}

export default AddTask;
